### ISSUE TITLE
[BUG] Sequences in fasta do not all have the same number of columns

### ISSUE THREAD

**Issue by jasonkim8652** [seoklab/RoseTTAFold-All-Atom#2]
### Describe the bug

While I running posebuster set(total: 428), 160 of them has these error. I ran this in nova001

```
- 09:39:14.486 ERROR: B
- 09:39:14.486 ERROR: Error in /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhalignment.cpp:1244: Compress:

- 09:39:14.486 ERROR:   sequences in 7SCW.fasta do not all have the same number of columns,

- 09:39:14.486 ERROR:
e.g. first sequence and sequence /home/ccaa2013/GalaxyDock4/posebusters/posebusters_benchmark_set/7SCW_GSP/7SCW_GSP_protein.pdb:chain.

- 09:39:14.486 ERROR: Check input format for '-M a2m' option and consider using '-M first' or '-M 50'

Error executing job with overrides: []
Traceback (most recent call last):
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 213, in main
    runner.infer()
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 160, in infer
    self.parse_inference_config()
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 50, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/data/protein.py", line 92, in generate_msa_and_load_protein
    msa_file, hhr_file, atab_file = make_msa(fasta_file, chain, model_runner)
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/data/preprocessing.py", line 42, in make_msa
    _ = subprocess.run(search_command, check=True)
  File "/opt/conda/envs/rf2aa/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make_msa.sh', '7SCW.fasta', PosixPath('7SCW/A'), '4', '64', PosixPath('/store/RF2AA/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt'), PosixPath('/store/RF2AA/pdb100/pdb100_2021Mar03'), PosixPath('/store/RF2AA/uniclust/UniRef30_2021_03')]' returned non-zero exit status 1.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

However, I make seqeunce file with same column length(maximum 100) like below

```
> /home/ccaa2013/GalaxyDock4/posebusters/posebusters_benchmark_set/7SCW_GSP/7SCW_GSP_protein.pdb:chain A
GSMTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFEDIHHYRE
QIKRVKDSEDVPMVLVGNKSDLPSRTVDTKQAQDLARSYGIPFIETSAKTRQGVDDAFYTLVREIRKHKEK
> /home/ccaa2013/GalaxyDock4/posebusters/posebusters_benchmark_set/7SCW_GSP/7SCW_GSP_protein.pdb:chain B
DTCIIRISVEDNNGNMYKSIMLTSQDKTPAVIQRAMLKHNLDSDPAEEYELVQVISEDKELVIPDSANVFYAMNSQVNFDFILRKK
```

Do I need to check the whitespace also? 

Please help me.

**Comment by jnooree** [comment]
Please attach full log.

**Comment by jasonkim8652** [comment]
```
/opt/conda/envs/rf2aa/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'input_7SCW': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/chemical.py:20: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /opt/conda/conda-bld/pytorch_1708025831440/work/aten/src/ATen/native/Cross.cpp:63.)
  Z = torch.cross(Xn,Yn)
^MPredicting 1/6:   0%|          | 0/2 [00:00<?, ?sequences/s]^MPredicting 1/6: 100%|██████████| 2/2 [00:02<00:00,  1.28s/sequences]^MPredicting 1/6: 100%|██████████| 2/2 [00:02<00:00,  1.28s/sequences]
^MPredicting 2/6:   0%|          | 0/2 [00:00<?, ?sequences/s]^MPredicting 2/6: 100%|██████████| 2/2 [00:02<00:00,  1.09s/sequences]^MPredicting 2/6: 100%|██████████| 2/2 [00:02<00:00,  1.09s/sequences]
^MPredicting 3/6:   0%|          | 0/2 [00:00<?, ?sequences/s]^MPredicting 3/6: 100%|██████████| 2/2 [00:02<00:00,  1.15s/sequences]^MPredicting 3/6: 100%|██████████| 2/2 [00:02<00:00,  1.15s/sequences]
^MPredicting 4/6:   0%|          | 0/2 [00:00<?, ?sequences/s]^MPredicting 4/6: 100%|██████████| 2/2 [00:02<00:00,  1.05s/sequences]^MPredicting 4/6: 100%|██████████| 2/2 [00:02<00:00,  1.05s/sequences]
^MPredicting 5/6:   0%|          | 0/2 [00:00<?, ?sequences/s]^MPredicting 5/6: 100%|██████████| 2/2 [00:02<00:00,  1.02s/sequences]^MPredicting 5/6: 100%|██████████| 2/2 [00:02<00:00,  1.02s/sequences]
^MPredicting 6/6:   0%|          | 0/2 [00:00<?, ?sequences/s]^MPredicting 6/6: 100%|██████████| 2/2 [00:02<00:00,  1.02s/sequences]^MPredicting 6/6: 100%|██████████| 2/2 [00:02<00:00,  1.02s/sequences]
- 09:39:14.486 ERROR: B
- 09:39:14.486 ERROR: Error in /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhalignment.cpp:1244: Compress:

- 09:39:14.486 ERROR:   sequences in 7SCW.fasta do not all have the same number of columns,

- 09:39:14.486 ERROR:
e.g. first sequence and sequence /home/ccaa2013/GalaxyDock4/posebusters/posebusters_benchmark_set/7SCW_GSP/7SCW_GSP_protein.pdb:chain.

- 09:39:14.486 ERROR: Check input format for '-M a2m' option and consider using '-M first' or '-M 50'

Error executing job with overrides: []
Traceback (most recent call last):
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 213, in main
    runner.infer()
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 160, in infer
    self.parse_inference_config()
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 50, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/data/protein.py", line 92, in generate_msa_and_load_protein
    msa_file, hhr_file, atab_file = make_msa(fasta_file, chain, model_runner)
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/data/preprocessing.py", line 42, in make_msa
    _ = subprocess.run(search_command, check=True)
  File "/opt/conda/envs/rf2aa/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make_msa.sh', '7SCW.fasta', PosixPath('7SCW/A'), '4', '64', PosixPath('/store/RF2AA/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt'), PosixPath('/store/RF2AA/pdb100/pdb100_2021Mar03'), PosixPath('/store/RF2AA/uniclust/UniRef30_2021_03')]' returned non-zero exit status 1.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by jnooree** [comment]
Can you run the same job without setting `-e` option in slurm?

**Comment by jasonkim8652** [comment]
```
/opt/conda/envs/rf2aa/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'input_7SCW': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/chemical.py:20: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /opt/conda/conda-bld/pytorch_1708025831440/work/aten/src/ATen/native/Cross.cpp:63.)
  Z = torch.cross(Xn,Yn)
Predicting 1/6: 100%|██████████| 2/2 [00:02<00:00,  1.25s/sequences]
Predicting 2/6: 100%|██████████| 2/2 [00:02<00:00,  1.18s/sequences]
Predicting 3/6: 100%|██████████| 2/2 [00:02<00:00,  1.10s/sequences]
Predicting 4/6: 100%|██████████| 2/2 [00:02<00:00,  1.11s/sequences]
Predicting 5/6: 100%|██████████| 2/2 [00:02<00:00,  1.21s/sequences]
Predicting 6/6: 100%|██████████| 2/2 [00:02<00:00,  1.13s/sequences]
Running HHblits against UniRef30 with E-value cutoff 1e-10
- 14:19:38.616 ERROR: B
- 14:19:38.616 ERROR: Error in /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhalignment.cpp:1244: Compress:

- 14:19:38.616 ERROR:   sequences in 7SCW.fasta do not all have the same number of columns,

- 14:19:38.616 ERROR:
e.g. first sequence and sequence /home/ccaa2013/GalaxyDock4/posebusters/posebusters_benchmark_set/7SCW_GSP/7SCW_GSP_protein.pdb:chain.

- 14:19:38.616 ERROR: Check input format for '-M a2m' option and consider using '-M first' or '-M 50'

Using the cif atom ordering for TRP.
['make_msa.sh', '7SCW.fasta', PosixPath('7SCW/A'), '4', '64', PosixPath('/store/RF2AA/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt'), PosixPath('/store/RF2AA/pdb100/pdb100_2021Mar03'), PosixPath('/store/RF2AA/uniclust/UniRef30_2021_03')]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 213, in main
    runner.infer()
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 160, in infer
    self.parse_inference_config()
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 50, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/data/protein.py", line 92, in generate_msa_and_load_protein
    msa_file, hhr_file, atab_file = make_msa(fasta_file, chain, model_runner)
  File "/opt/conda/envs/rf2aa/lib/python3.10/site-packages/rf2aa/data/preprocessing.py", line 42, in make_msa
    _ = subprocess.run(search_command, check=True)
  File "/opt/conda/envs/rf2aa/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make_msa.sh', '7SCW.fasta', PosixPath('7SCW/A'), '4', '64', PosixPath('/store/RF2AA/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt'), PosixPath('/store/RF2AA/pdb100/pdb100_2021Mar03'), PosixPath('/store/RF2AA/uniclust/UniRef30_2021_03')]' returned non-zero exit status 1.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Execution Time: 73 seconds
```

**Comment by jnooree** [comment]
All sequences in the input fasta must be of the same length (seemingly). Split each chain into its own fasta file.

**Comment by jasonkim8652** [comment]
I solved this problem by splitting each chain. I'll close this issue.
